### PR TITLE
Use unnamed consts in chalk-derive

### PR DESCRIPTION
**Pull request by flodiebold**
This makes the derives work in rust-analyzer.

CC rust-analyzer/rust-analyzer#9562

### CODE REVIEW

**Comment by lnicola** [comment]
What about `derive_visit` and `derive_super_visit`? But yeah, I got the same error :grimacing:.

**Comment by flodiebold** [comment]
`derive_visit` and `derive_super_visit` both call `derive_any_visit`.

:confused: no idea what's going on with these errors, the generated code looks fine...

**Comment by lnicola** [comment]
But there's a semicolon at the end of https://github.com/mystor/synstructure/pull/43/files.

**Comment by flodiebold** [comment]
Not in the one further up, there seem to be two versions. That would explain why it worked for the original author.

**Comment by flodiebold** [comment]
I've tried rewriting the derives to `gen_impl`, but it's rather annoying to do.

**Comment by lnicola** [comment]
Yeah, it seems so. I files a PR against synstructure in the meanwhile, but it might take a while to get merged and published.

Maybe we should also work around this on our side?

**Comment by flodiebold** [comment]
I made a PR for my hacky workaround :shrug:

**Comment by flodiebold** [comment]
New synstructure version got released, so it works now :slightly_smiling_face:

**Comment by lnicola** [comment]
@shepmaster ugh

**Comment by lqd** [comment]
This looks like github being confused about which PR in which fork actually caused this issue to be closed, it was because of Florian's "until the proper fix $this-issue" message would close this issue when the PR was merged.
image

**Comment by lnicola** [comment]
Yep. Surprisingly, though, GitHub didn't close this when bors merged the original PR in the RA repo.

**Comment by lqd** [comment]
Very confusing indeed

**Comment by shepmaster** [comment]
Very odd!

My workflow involves pulling from my `upstream` (rust-analyzer/rust-analyzer) and pushing to my `origin` (shepmaster/rust-analyzer). I've never had this behavior happen before.

**Comment by shepmaster** [comment]
I've also never seen it cross repositories before (rust-analyzer -> chalk), which is doubly strange.

**Comment by jackh726** [comment]
Not sure what the problem is here, but sure. @bors r+

**Comment by lnicola** [comment]
> Not sure what the problem is here, but sure.

`rust-analyzer` only looks into unnamed consts for trait implementations, to speed up the analysis.

**Pull request merged**
