### PR TITLE
Introduce Tracing into Chalk

### PR DESCRIPTION
**Pull request by davidbarsky**
c.c. #337

This is super WIP and _nowhere_ near ready being merged.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Closing in favor of #394 -- let's revisit this stuff once that one lands.

**Comment by nikomatsakis** [comment]
Wait, I put that comment on the wrong PR :)

**Comment by jackh726** [comment]
So, @davidbarsky has indicated on Zulip that they're not going to have time for now to get this pushed forward. However, this is actually pretty close. So, I'm gonna actually mark this as a "good first issue" if someone wants to pick this up get this mergeable. (If not, I'll get to it eventually)

**Comment by nolanderc** [comment]
I will attempt to pick this back up.

**Comment by davidbarsky** [comment]
Closed in favor of https://github.com/rust-lang/chalk/pull/409.

**Pull request closed without merging**
