### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by detrumi**

### CODE REVIEW

**Comment by detrumi** [comment]
Woah, ICE on the nightly build:
````
   Compiling chalk-integration v0.19.0-dev.0 (/home/runner/work/chalk/chalk/chalk-integration)
error: internal compiler error: src/librustc_middle/ty/subst.rs:554:17: type parameter `S/#2` (S/2) out of range when substituting (root type=Some(for<'r> fn(&'r std::iter::Chain<std::iter::Map<std::vec::IntoIter<chalk_ir::Ty<interner::ChalkIr>>, [closure@chalk_solve::wf::WfSolver::<'db, I, S, SC>::verify_adt_decl::{{closure}}#1::{{closure}}#1::{{closure}}#0::{{closure}}#0 0:&&interner::ChalkIr]>, std::option::IntoIter<chalk_ir::Goal<interner::ChalkIr>>>) -> (usize, std::option::Option<usize>) {<std::iter::Chain<std::iter::Map<std::vec::IntoIter<chalk_ir::Ty<interner::ChalkIr>>, [closure@chalk_solve::wf::WfSolver::<'db, I, S, SC>::verify_adt_decl::{{closure}}#1::{{closure}}#1::{{closure}}#0::{{closure}}#0 0:&&interner::ChalkIr]>, std::option::IntoIter<chalk_ir::Goal<interner::ChalkIr>>> as std::iter::Iterator>::size_hint})) substs=[for<'r> fn(&'r std::iter::Chain<std::iter::Map<std::vec::IntoIter<chalk_ir::Ty<interner::ChalkIr>>, [closure@chalk_solve::wf::WfSolver::<'db, I, S, SC>::verify_adt_decl::{{closure}}#1::{{closure}}#1::{{closure}}#0::{{closure}}#0 0:&&interner::ChalkIr]>, std::option::IntoIter<chalk_ir::Goal<interner::ChalkIr>>>) -> (usize, std::option::Option<usize>) {<std::iter::Chain<std::iter::Map<std::vec::IntoIter<chalk_ir::Ty<interner::ChalkIr>>, [closure@chalk_solve::wf::WfSolver::<'db, I, S, SC>::verify_adt_decl::{{closure}}#1::{{closure}}#1::{{closure}}#0::{{closure}}#0 0:&&interner::ChalkIr]>, std::option::IntoIter<chalk_ir::Goal<interner::ChalkIr>>> as std::iter::Iterator>::size_hint}, (&std::iter::Chain<std::iter::Map<std::vec::IntoIter<chalk_ir::Ty<interner::ChalkIr>>, [closure@chalk_solve::wf::WfSolver::<'db, I, S, SC>::verify_adt_decl::{{closure}}#1::{{closure}}#1::{{closure}}#0::{{closure}}#0 0:&&interner::ChalkIr]>, std::option::IntoIter<chalk_ir::Goal<interner::ChalkIr>>>,)]

thread 'rustc' panicked at 'Box<Any>', /rustc/8ad7bc3f428300aee6764f6e23527e19eb235e81/src/libstd/macros.rs:13:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``

**Comment by jackh726** [comment]
Actually, I think the ICE is slightly worse than the linked issue, since this isn't triggered by an associated const (at least in Chalk's code). Worse even still, the linked issue and the other issues linked from there seem to point to const eval-relatedness. And we aren't doing that. So I think we should file an issue, especially given this must have been a very recent regression.

**Comment by nathanwhit** [comment]
Shoot, I forgot that resolving conflicts through Github makes a merge commit 🤦, my bad. Can you rebase @detrumi?

**Comment by jackh726** [comment]
@nathanwhit you should be able to rebase too :)

**Comment by nathanwhit** [comment]
I always forget that's a thing you can do 😅. I figure this is probably ready to merge now?

**Pull request merged**
