### PR TITLE
Remove TypeName and merge into TyKind

### PR DESCRIPTION
**Pull request by jackh726**

### CODE REVIEW

**Review by matthewjasper — APPROVED** [review]

**Comment by matthewjasper** [comment]
Let's see if bors will listen to me...
@bors r+

**Comment by camelid** [comment]
Hmm, this broke links in the docs but bors still merged it.

**Comment by jackh726** [comment]
@camelid we specifically *don't* block merge on linkcheck; we've seen false positives before and in general don't want it to hold up CI anyways

**Comment by camelid** [comment]
Ah, well the linkchecker caught that `TypeName` was referenced and thus the docs are out of date.

**Pull request merged**
