### PR TITLE
Extend well-known traits by Unpin

### PR DESCRIPTION
**Pull request by memoryleak47**
I read the RFC and didn't find any special rules concerning Unpin, so this one is rather straight-forward. Correct me if I missed something!
cc #363

### CODE REVIEW

**Review by jackh726 — CHANGES_REQUESTED** [review]
I don't think this is right. I think `Unpin` needs to be implemented for all the built in types. Std has impls for all scalars, ref, raws; but we need builtin impls for function pointers, function defs, arrays, `str`, closures, slices(?).

**Comment by jackh726** [comment]
Also, please update the well known traits table in the book.

**Comment by memoryleak47** [comment]
I thought this was a consequence of defining it as an auto trait. I'll look into it.

**Review by jackh726 — APPROVED** [review]
LGTM! Pretty straightfoward until we get generators and auto traits for builtin types.

**Pull request merged**
