### PR TITLE
Remove unused Result assoc type from Fold trait

### PR DESCRIPTION
**Pull request by eggyal**
r? @jackh726

### CODE REVIEW

**Comment by eggyal** [comment]
Broken doc links look good from here, but evidently not working in CI.

**Comment by detrumi** [comment]
Doc links are fixed now. No need to retry the build since the main build succeeded already.

**Comment by jackh726** [comment]
After #767 lands, this will need a rebase. LGTM

**Comment by eggyal** [comment]
Rebase off #767 [as discussed on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/144729-t-types/topic/Aligning.20rustc.20and.20chalk.20folding.2Fvisiting.20traits/near/286979357).

**Pull request merged**
