### PR TITLE
document opaque types

### PR DESCRIPTION
**Pull request by nikomatsakis**
cc @detrumi -- I am working to document opaque types. Probably nothing in here is really surprising to you =)

### CODE REVIEW

**Comment by jackh726** [comment]
@nikomatsakis is this "complete"? If so, maybe @detrumi wants to review. Looks like some doc test errors and link check error regardless.

**Comment by nikomatsakis** [comment]
I forgot we hadn't merged this yet! I don't thnk it's *complete* but I think it was *mergeable*

**Comment by nikomatsakis** [comment]
I'll go back and fix tests

**Pull request merged**
