### PR TITLE
Use FxHashMap/FxHashSet and add well-formed clause for tuples

### PR DESCRIPTION
**Pull request by jackh726**

### CODE REVIEW

**Comment by bjorn3** [comment]
Using `FxHashMap` and `FxHashSet` makes it harder to detect cases where the output depends on the iteration order, as they don't use a random number in their hashes, unlike `HashMap` and `HashSet`, which means that simply rerunning won't show the problem.

**Comment by jackh726** [comment]
Unfortunately, we can't build through rustc without using them. But I'm not sure if we really prefer to randomize order anyways.

**Comment by bjorn3** [comment]
Maybe do it behind a feature flag that is enabled on CI, but disabled for rustc. That way the rustc lint won't find it, but CI will still catch being dependent on iteration order.

**Comment by jackh726** [comment]
We already use FxHashMap elsewhere. And I wouldn't want to rely on there *maybe* being a different order. It's not a bad idea to have tests where we which around iteration order. But I would rather that be explicit.

**Comment by flodiebold** [comment]
I agree, I originally intended to change this to `FxHashSet` anyway but forgot.

**Pull request merged**
