### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by basavesh**
A simple typo fix, found while reading the book.

### CODE REVIEW

**Review by detrumi — APPROVED** [review]
Good catch, thanks for fixing that!

@bors r+

**Comment by basavesh** [comment]
@detrumi  I see similar stuff in https://rust-lang.github.io/chalk/book/types.html too. Should I create an another PR?

> The AST. This is used purely for writing test cases with a Rust-like syntax. This is consumed by lowering code, which takes AST and products Rust IR (the next bullet point).
> The Rust IR. This is a "HIR-like" notation that defines the interesting properties of things like traits, impls, and structs. It is an input to the rules code, which produces

**Comment by detrumi** [comment]
Hm, why didn't bors merge yet?

@bors r+

**Pull request merged**
