### PR TITLE
Always relate with Invariant to non-General inference vars

### LINKED ISSUE #658: Regression with unification within fn (?)
See https://github.com/rust-analyzer/rust-analyzer/issues/6628.

I've got this down to the following Chalk test:
```rust
#[test]
fn ambiguous_unification_in_fn() {
    test! {
        program {
            trait FnOnce<Args> {
                type Output;
            }

            struct MyClosure<T> {}
            impl<T> FnOnce<(T,)> for MyClosure<fn(T) -> ()> {
                type Output = ();
            }
        }
        goal {
            exists<int T, U> {
                MyClosure<fn(&'static U) -> ()>: FnOnce<(&'static T,)>
            }
        } yields {
            "Unique"
        }
    }
}
```

This succeeded before #609 and now fails with an ambiguous result.

CC @jackh726  @daboross

### PR DESCRIPTION
**Pull request by jackh726**
Fixes #658 

An alternative way to approach this is to always unify inference variables as `Invariant`, which is how it's implemented in rustc right now. We should think about if we want that long term though (and possibly come up with tests that hit that).

### CODE REVIEW

**Comment by matthewjasper** [comment]
Rustc doesn't unify inference variables with subtype bounds:

https://github.com/rust-lang/rust/blob/b776d1c3e3db8befabb123ebb1e46c3531eaed46/compiler/rustc_infer/src/infer/sub.rs#L87-L112

Looking at unification, the only difference here with rustc in this area is that `{int_var} <: {ty_var}` is turned into `{int_var} = {ty_var}` (and likewise with floats, and with the subtype relation reversed).

**Comment by jackh726** [comment]
> Looking at unification, the only difference here with rustc in this area is that `{int_var} <: {ty_var}` is turned into `{int_var} = {ty_var}` (and likewise with floats, and with the subtype relation reversed).

Ugh yeah, that's what I was missing and what the proper change is.

**Comment by jackh726** [comment]
Actually, that alone is not enough to make the test pass :/

**Comment by matthewjasper** [comment]
I'm not sure if the test case with two arbitrary variables needs to pass. One of the variables will eventually be resolved if the program is going to compile.

**Comment by jackh726** [comment]
I wondered about that. I did test with the original test from @flodiebold with the `int T` and that didn't pass.

**Comment by nikomatsakis** [comment]
I don't love this solution. Like @matthewjasper, I'm not sure that the test with two *arbitrary variables* needs to pass. @jackh726 can you share what you tried with integer variables? In rustc, we definitely consider integer variables "more specific" than normal variables (so e.g. a general variable would be "assigned" the value of an integer variable).

**Comment by jackh726** [comment]
Yeah, I updated.

**Comment by jackh726** [comment]
So, to elaborate on why only always unifying non-general inference vars doesn't work:
First, we start off trying to unify our goal `Implemented(MyClosure<"rust" for<0> [?0 := (&'static ?0), ?1 := 0]>: FnOnce<1<(&'static ?1i)>>)` with our (instantiated) clause `Implemented(MyClosure<"rust" for<0> [?0 := ?2, ?1 := 0]>: FnOnce<1<?2>>)`.

From there, we try to unify `MyClosure<"rust" for<0> [?0 := (&'static ?0), ?1 := 0]>` and `MyClosure<"rust" for<0> [?0 := ?2, ?1 := 0]>` first. When `?2` tries to get unified with `(&'static ?0)`, it is generalized and set to `(&'?3 ?4)`. From the next unification, we get `?4 < ?0` (and the reverse too, since both `Covariant` and `Contravariant`, since we're in `Invariant`).

By this point, when we unify `1<(&'static ?1i)>` and `1<?2>`, it's too late, and we've already added the subtype goals.

**Comment by jackh726** [comment]
Okay, so we probably just need to actually resolve inference vars when trying to simplify a subtype goal...

**Comment by jackh726** [comment]
Okay so that worked.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
oops, I forgot, we use bors now don't we... d'oh

**Pull request merged**
