### PR TITLE
Add "Recursive solver coinduction chapter" to book todo list

### PR DESCRIPTION
**Pull request by nico-abram**

### CODE REVIEW

**Comment by jackh726** [comment]
Did you see http://rust-lang.github.io/chalk/book/engine/logic/coinduction.html?

**Comment by nico-abram** [comment]
Oh, I was thinking of https://rust-lang.github.io/chalk/book/recursive/coinduction.html

**Comment by jackh726** [comment]
@nico-abram oh, didn't see that. Can you change it to "Recursive solver coinduction chapter"

**Comment by nico-abram** [comment]
Sure thing! It is done

**Comment by jackh726** [comment]
I meant in the book, not the title 🤣

**Comment by nico-abram** [comment]
Yeah, sorry. I forgot to actually input my credentials into git after doing a git push and just realized it was still waiting for them 🤣

**Comment by jackh726** [comment]
Thanks!

@bors r+

**Pull request merged**
